name: build_panel_number_two

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: push
jobs:
  Create-Base-UF2:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up environment
        run: |
          sudo apt-get install gcc-arm-none-eabi libnewlib-arm-none-eabi
          arm-none-eabi-gcc --version
      - name: Build micropython
        run: |
          git clone https://github.com/micropython/micropython.git
          cd micropython
          make -C mpy-cross
          cp ../main.py ports/rp2/modules/main.py
          cd ports/rp2
          make BOARD=RPI_PICO_W submodules
          make BOARD=RPI_PICO_W clean
          make BOARD=RPI_PICO_W
      - name: Upload compiled UF2 to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: micropython/ports/rp2/build-RPI_PICO_W/firmware.uf2
      - name: Job outcome
        run: echo "This job's status is ${{ job.status }}."